bootstrap.servers: "kafka-1:9092"
streams:
  schema.registry.url: "http://app01-ted-pp.phys.pack:8081"
  specific.avro.reader: true

topic:
  aggregateClientIptv : "appna_kafka_streaming_mac_avro_in_iptvliveagg001"
  eventIptvJson : "app1929_kafka_streaming_null_json_to_iptvlive001"
  eventIptvAvro : "appna_kafka_streaming_mac_avro_in_iptvlive002"
  referentialClientJson : "app3034_hdfs_batch_mac_json_to_refclient001"
  referentialClientAvro : "appna_kafka_batch_mac_avro_in_refclient002"
  audience : "appna_kafka_streaming_groupid_avro_in_audience001"

configs :
  maccounttopology:
    windowSizeMs : "60000"
    windowGracePeriodMs : "5000"
    inactivityMs : "600000"

